# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/texsis.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_rx_0_0/design_1_uart_rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_uart_rx_0_0 || ORIG_REF_NAME==design_1_uart_rx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sample_packer_0_0/design_1_sample_packer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sample_packer_0_0 || ORIG_REF_NAME==design_1_sample_packer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_counter_0_0/design_1_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_counter_0_0 || ORIG_REF_NAME==design_1_counter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_2/design_1_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_2 || ORIG_REF_NAME==design_1_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_top_k_sort_0_0/design_1_top_k_sort_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_top_k_sort_0_0 || ORIG_REF_NAME==design_1_top_k_sort_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_selection_label_0_0/design_1_selection_label_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_selection_label_0_0 || ORIG_REF_NAME==design_1_selection_label_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_packer_0_0/design_1_uart_packer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_uart_packer_0_0 || ORIG_REF_NAME==design_1_uart_packer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_tx_0_0/design_1_uart_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_uart_tx_0_0 || ORIG_REF_NAME==design_1_uart_tx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_timer_0_0/design_1_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_timer_0_0 || ORIG_REF_NAME==design_1_timer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_manhattan_distance_0_1/design_1_manhattan_distance_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_manhattan_distance_0_1 || ORIG_REF_NAME==design_1_manhattan_distance_0_1} -quiet] -quiet

# XDC: c:/Users/diego/OneDrive/Escritorio/tesis_de_mierda/tesis_de_mierda.gen/sources_1/bd/design_1/design_1_ooc.xdc
